### ISSUE TITLE
Problem with snap_deep_copy

### ISSUE THREAD

**Issue by dTrksak** [JujuAdams/SNAP#1]
First off, thanks a bunch for creating these scripts, incredibly useful.
My issue is that snap_deep_copy does not copy static variables or methods from the original constructor. I fixed that by doing this:

static copy_struct = function(_source)
{
	var _structName = asset_get_index(instanceof(_source));
	var _copy = {};
	if(script_exists(_structName))
		_copy = new _structName();
... etc ...
}

it only runs the new _structName() if _structName is a constructor because of script_exists(), this is to not mess up any normal structs by trying to construct them.

**Comment by JujuAdams** [comment]
Ah interesting. I would bet that your copy no longer returns the correct value for `instanceof()` as well?

**Comment by dTrksak** [comment]
With your original code and setting _value to a struct created by a constructor, running instanceof() on the output just returns 'struct', but with this edit, it returns the correct constructor if a constructor was the original input.
An example:

function const() constructor
{
	normalVar = 0;
	static staticVar = 1;
	static staticFunc = function() {print("this works")}
}
const1 = new const();
copiedConst1 = new_snap_deep_copy(const1); //Snap with my edit
print(instanceof(copiedConst1 )); //Outputs 'const_gml_Object_oController_Create_0'
print(copiedConst1.normalVar) //Outputs 0
print(copiedConst1.staticVar) //Outputs 1
copiedConst1.staticFunc() //Outputs this works

copiedConst2 = old_snap_deep_copy(const1); //Original snap
print(instanceof(copiedConst2)); //Outputs 'struct'
print(copiedConst2.normalVar) //Outputs 0
print(copiedConst2.staticVar) //Outputs an error, unknown object not set before reading it
copiedConst2.staticFunc() //Outputs an error, unknown object not set before reading it
