### ISSUE TITLE
Function name mismatch deep/shallow add

### ISSUE THREAD

**Issue by Grisgram** [JujuAdams/SNAP#22]
See images -- the shallow add script holds the wrong function or the name is just mistyped?

![image](https://user-images.githubusercontent.com/19487451/181260836-dd706ab3-6c3a-4221-b983-c8a852d3faf2.png)
![image](https://user-images.githubusercontent.com/19487451/181260858-d8e51ba4-a9a5-455a-8eab-0a468298c957.png)

**Comment by JujuAdams** [comment]
ugh
