### ISSUE TITLE
foreach method doesn't execute in scope

### ISSUE THREAD

**Issue by prtksxna** [JujuAdams/SNAP#24]
Note: This might be the intended behavior, or a limitation of GameMaker. So please feel free to close.

```gml
isAnythingHovering = function () {
	var _isHovering = false;
	foreach(things, function (_thing) {
		if (_thing.isHovering == true) _isHovering = true;
	});
	/*for (var _i = 0; _i < array_length(things); _i += 1) {
		var _thing = things[_i];
		if (_thing.isHovering == true) _isHovering = true;
	}*/
	return _isHovering;
}
```

In the following code, the callback function doesn't have access to and is unable to change the `_isHovering` local variable.

**Comment by JujuAdams** [comment]
GML doesn't allow functions to access local variables in other functions, even if that function is on the callstack. Regretably, this is a limitation that is not possible to automatically work around. Best approach here is to make a clumsy temporary global variable.

**Comment by prtksxna** [comment]
Ah got it. Thanks Juju!
