### ISSUE TITLE
Wiki lists "array2D" type instead of "string" for snap_from_csv() function

### ISSUE THREAD

**Issue by NoFluxGiven** [JujuAdams/SNAP#26]
As per title, [snap_from_csv()](https://github.com/JujuAdams/SNAP/wiki/CSV#snap_from_csvarray2d-celldelimiter-stringdelimiter) lists the arguments as `array2D, [cellDelimiter], [stringDelimiter]` in the preview, whereas it should be `string, [cellDelimiter], [stringDelimiter]`.

**Comment by JujuAdams** [comment]
Thanks for reporting this. I'm in the middle of refactoring the library so I will address this at the same time as pushing out a new version.
