### ISSUE TITLE
SnapToJSON - edge case with empty struct

### ISSUE THREAD

**Issue by MichelVGameMaker** [JujuAdams/SNAP#30]
While trying to save config. data from Evoleo's LDTKparser, I noticed an error while saving... I think due to the struct having empty values for some keys... I have iterated a bit to simplify the struct.

**The code is as follow and returns the error at the end**
global.__ldtk_config      = {
	file: "",
	mappings: { 
		levels: {	},
        }
}
global.__ldtk_config = SnapFromJSON(SnapToJSON(global.__ldtk_config));

**Note that it woks, if I only keep the struct as follow (deleting the "file" key)**
global.__ldtk_config      = {
	mappings: { 
		levels: {	},
        }
}
global.__ldtk_config = SnapFromJSON(SnapToJSON(global.__ldtk_config));

**The error is**
Setting scheduler resolution to 1
Attempting to set gamepadcount to 12
DirectX11: Using hardware device
Collision Event time(microsecs)=2
ERROR!!! :: ############################################################################################
ERROR in
action number 1
of Create Event
for object <undefined>:
variable_struct_set argument 1 incorrect type (undefined) expecting a Number (YYGI32)
 at gml_Script_SnapBufferReadJSON (line 90) -                     _stackTop[$ _structKey] = _value;
############################################################################################
gml_Script_SnapBufferReadJSON (line 90)
gml_Script_SnapFromJSON (line 12) -     var _data = SnapBufferReadJSON(_buffer, 0);
gml_GlobalScript_test (line 13) - global.__ldtk_config = SnapFromJSON(SnapToJSON(global.__ldtk_config));
C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.0.12/windows/x64/Runner.exe exited with non-zero status (1)
elapsed time 00:00:20.3054405s for command "C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.0.12/bin/igor/windows/x64/Igor.exe" -j=8 -options="C:\Users\Michel\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\build.bff" -v -- Windows Run started at 12/03/2022 18:55:28

**Comment by MichelVGameMaker** [comment]
**TubularElf solved it on december 3 at 20:59 french time**

In script SnapBufferWriteJSON.gml add at line 159 buffer_seek(_buffer, buffer_seek_relative, -1);

SNAP is trying to decrement back by 1 and set }, which normally is fine since whenever there's a key x value pair, adds a comma. Which all this line does is decrement by 1 and replace said comma.
But what happens when there's no keys at all? Nothing is processed, and therefore no comma is put into place. And therefore... { becomes }

an obvious fix to me is by adding at line 159 if (_count > 0), next to buffer_seek(_buffer, buffer_seek_relative, -1);

**Comment by JujuAdams** [comment]
Offical fix here: https://github.com/JujuAdams/SNAP/commit/c443c8e873d1953c6bfe2c1076e2eef0661a99c5
