### ISSUE TITLE
SnapFromJson() omits the end of a path

### ISSUE THREAD

**Issue by MichelVGameMaker** [JujuAdams/SNAP#31]
A json file with this content: {"file":"C:\\Users\\Michel\\Desktop\\LDTK\\samples\\AutoLayers_1_basic.ldtk"} (with double \ \  and not single \  )
is parsed to { file : "C:\Users\Michel\Desktop\LDTK\samples\" }
omitting the last part of the path

Test code is:
global.test_me =     { file:  "",    };
var _file   = get_open_filename("*.ldtk", "");
global.test_me.file = _file;
show_debug_message("a1", global.test_me);
SnapStringToFile(SnapToJSON(global.test_me), "test_me.json");
global.test_me = SnapFromJSON(SnapStringFromFile("test_me.json"));
 show_debug_message("a2", global.test_me);`

**Comment by JujuAdams** [comment]
Fixed https://github.com/JujuAdams/SNAP/commit/fbc91b627342721d4956800fecfe30382cd9982f
