### ISSUE TITLE
Bug with YAML handling 2D arrays

### ISSUE THREAD

**Issue by ArendPeter** [JujuAdams/SNAP#32]
Hello! I imported your library to allow for YAML parsing and it's been super helpful so far :)

I noticed a bug while trying to parse 2D arrays

Input YAML

```
-
  - 1
  - 2
-
  - 3
  - 4
```

Expected Output

```
[
  [1,2],
  [3,4]
]
```

Actual Output

```
[
 [ 1 ],
 2,
 [ 3 ],
 4 
] 
```

I confirmed this using both tabs and spaces

I was also used these source to verify the expected output
https://www.json2yaml.com/
https://stackoverflow.com/a/49725357

I worked around by using the following format, but I figured I'd report it anyway

```
- - 1
  - 2
- - 3
  - 4
```

**Comment by JujuAdams** [comment]
Thanks for reporting this. I'm off on holiday today so won't have a chance to look at this until next week.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/SNAP/commit/4736cff3b512b2288fdc7b9eb1acdf4d0cdd7a05
