### ISSUE TITLE
VDF

### ISSUE THREAD

**Issue by offalynne** [JujuAdams/SNAP#33]
https://developer.valvesoftware.com/wiki/KeyValues

Steam uses Valve's KeyValues format (colloquially "VDF" for Valve Data Format, originating from the Source Engine) for app configuration. There are a few reasons this would be useful, most immediately obvious a more thorough Steam Input integration for [Input](https://github.com/JujuAdams/Input), currently configured only for "Gamepad Emulation" mode.

Another potential use is unifying platform integrations such as achievements, DLC and [UGC](https://partner.steamgames.com/doc/features/workshop/implementation) management, etc.

Not expecting anyone else to implement this, but not going to self-assign for the time being in case someone else is so inclined :-)

**Comment by JujuAdams** [comment]
Looks pretty easy. Do you have any real world examples that we could use for testing?

**Comment by offalynne** [comment]
From Valve:
- https://partner.steamgames.com/doc/features/steam_controller/iga_examples

Misc. tests:
- https://github.com/RoyalBingBong/vdfplus/blob/master/test/testfiles/test.vdf
- https://github.com/EXayer/vdf-converter/tree/main/tests/samples
- https://github.com/GerhardvanZyl/Steam-VDF-Converter/tree/master/VdfConverter.Test/InputFiles
- https://github.com/andygrunwald/vdf/tree/main/testdata
- https://github.com/CosmicHorrorDev/vdf-rs/tree/main/keyvalues-parser/tests/assets

Field data:
- https://github.com/DHager/hl2parse/tree/master/hl2parse-tests/src/test/resources/com/technofovea/hl2parse/vdf
- https://github.com/marshauf/keyvalues/tree/master/testdata
- https://github.com/Jleagle/steam-go/tree/master/steamvdf/testdata

**Comment by offalynne** [comment]
🥳🥳 thank you !!
