### ISSUE TITLE
XML being read incorrectly

### ISSUE THREAD

**Issue by NyakoFox** [JujuAdams/SNAP#40]
[testfiles.zip](https://github.com/JujuAdams/SNAP/files/13519047/testfiles.zip)

These two XML files have the same issue, being that XML parsing randomly breaks and starts taking some of the XML tag into its text contents. The lines it breaks on are consistent.

![image](https://github.com/JujuAdams/SNAP/assets/87289390/99e3b4cb-b8f1-4699-a659-1e11fa8537d1)

![image](https://github.com/JujuAdams/SNAP/assets/87289390/61b075b0-4084-40db-babe-ce4330cac787)

**Comment by JujuAdams** [comment]
Haven't confirmed this myself yet but I will look into it when I can.

**Comment by JujuAdams** [comment]
Ridiculous bug caused by me reusing a variable and GameMaker thinking `"62" == 62` https://github.com/JujuAdams/SNAP/commit/8d050ea870f834389c7934a70969070f2c4cb0d5
