### ISSUE TITLE
SNAP  edcode  messagepack error

### ISSUE THREAD

**Issue by Droog159** [JujuAdams/SNAP#7]
Encode:{ x : 300, y : 300, cmd : 10, mid : "WHRdAcBIZ", time : 10 }
error  Encode:85 a1 78 cd 2c a1 79 cd 2c a3 63 6d 64 0a a3 6d 69 64 a9 57 48 52 64 41 63 42 49 5a a4 74 69 6d 65 0a
right  Encode:85 A1 78 CD 01 2C A1 79 CD 01 2C A3 63 6D 64 0A A3 6D 69 64 A9 57 48 52 64 41 63 42 49 5A A4 74 69 6D 65 0A

**Comment by Droog159** [comment]
ooor look at line 233 in snap_to_messagepack()
change buffer_u8 to buffer_u16
that should fix it

**Comment by JujuAdams** [comment]
Fixed in [3.4.2](https://github.com/JujuAdams/SNAP/releases/tag/3.4.2)
