### ISSUE TITLE
Unable to compile for YYP

### ISSUE THREAD

**Issue by sakurah-dev** [JujuAdams/SNAP#9]
When I attempt to compile my game for YYP that's using SNAP, I run into issues with the `snap_from_messagepack` function, like below. I believe it's due to the way the arguments are handled as it uses argument_count.

```
gml_GlobalScript_snap_from_messagepack.gml.o : error LNK2019: unresolved external symbol "struct YYVAR g_Script_gml_Script____struct___15_anon___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack_275128___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack" (?g_Script_gml_Script____struct___15_anon___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack_275128___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack@@3UYYVAR@@A) referenced in function "struct YYRValue & __cdecl gml_Script____struct___15_anon___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack_275128___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack(class CInstance *,class CInstance *,struct YYRValue &,int,struct YYRValue * *)" (?gml_Script____struct___15_anon___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack_275128___snap_from_messagepack_parser_gml_GlobalScript_snap_from_messagepack@@YAAAUYYRValue@@PAVCInstance@@0AAU1@HPAPAU1@@Z)
```

I have tweaked my version of the scripts I have locally with it just using named arguments/parameters and checking `is_undefined` to ensure a default value is set and it compiles as expected.

Just thought I'd flag that if something like that should be fixed so the version works regardless of YYC or VM

**Comment by JujuAdams** [comment]
Hiya, what version of GM are you using, and what version of SNAP? I'm not seeing this error in 2.3.1.536 myself

Regardless, I've noticed a typo in `snap_from_messagepack()` where the argument indices are incorrect. I suspect this may be the cause of the problem as `argument_count` is stable everywhere else. This fix is available in [v3.4.3](https://github.com/JujuAdams/SNAP/releases/tag/3.4.3), and the actual change is [here](https://github.com/JujuAdams/SNAP/commit/80c740836929073ff28f622efe1707fb5656c798#diff-130f869bd46b2bce33273fd91220f71af8c46f43e978148bff31c6dacbf7d764)

Could you retest with this version please?

**Comment by sakurah-dev** [comment]
Apologies for delay, but I was able to build my project with the v3.4.3 so I believe this issue can be marked as resolved. Thanks.

**Comment by JujuAdams** [comment]
Excellent, thank you for testing it out!
